package Groups;

import javax.swing.*;

import ObjectReference.Frame;
import ObjectReference.TextArea;

import java.awt.*;

public class About {

    public About(){

        Frame frame = new Frame(new Dimension(800, 700),"About Groups");

        String[] lines = {"• A group (also known as a family) is a column of elements in the periodic table of the chemical elements.",
        "• There are 18 numbered groups in the periodic table; the f-block columns (between groups 2 and 3) are not numbered.",
        "• Elements in the same group have same number of valence electrons.",
        "• The elements in a group have similar physical or chemical characteristics of the outermost electron shells of their atoms",
        "• Groups may also be identified using their topmost element, or have a specific name.  For example, group 16 is also described as the \"oxygen group\" and as the \"chalcogens\".",
        "• There are three systems of group numbering for the groups. ",
        "•  The modern numbering system of \"group 1\" to \"group 18\" has been recommended by the International Union of Pure and Applied Chemistry (IUPAC) since about 1990."
        };

        String[][] groupLines = {{"• This group contains the alkali metals.", "• The alkali metals consist of Lithium, Sodium, Potassium, Rubidium, Caesium and Francium.", "• They have one electron in their outermost shell and therefore show a oxidation state of one .","• It lies in the s-block of the periodic table, meaning their outermost electron is in the s-orbital.", "• They are known as alkali metals because they react with water to form strong alkaline hydroxides.", "• Elements are very reactive and do not occur in free state, are soft and have low melting and boiling points.", "• All elements are ionic or electrovalent in nature.", "• All alkali metal salts impart color to the flame, e.g. lithium(crimson red), sodium(golden yellow), potassium(lilac) "},
                {"• This group contains the alkaline earth metals.", "• The alkaline earth metals consist of Be, Mg, Ca, Sr, Ba and Ra.", "• They have two electrons in their outermost shell and therefore show two oxidation state.", "• It lies in the s-block of the periodic table, meaning their outermost electron is in the s-orbital.", "• They are called as alkaline earth metals because their oxides occur in the earth's crust.", "• Their hydroxides are weak alkalies.", "• They are reactive metals and hence they do not occur in free state in nature.", "They are grayish white in color and harder and less reactive than alkali metals.", "• All elements except beryllium are ionic in nature.", "• Melting and boiling points are low but higher than alkali metals.", "• Except beryllium and magnesium, they impart color to the flame e.g. Calcium - brick red, Strontium - Crimson"},
                {"• Group 3 is the first group of transition metals in the periodic table.", "• It is generally agreed that this group contains  four elements : Scandium, yttrium, lawrencium and lutetium.", "• This group lies in the d-block of the periodic table, meaning the outermost electron is in the d-orbital.", "• They all have 3 valence electrons and the group oxidation state of +3 as a major one.", "• It is also called the scandium group or scandium family after its lightest member.", "• This group is closely related to the rare-earth elements.", "• All the group 3 elements are rather soft, silvery-white metals, although their hardness increases with atomic number.", "• They quickly tarnish in air and react with water, though their reactivity is masked by the formation of an oxide layer.", "• The first three of them occur naturally.", "• Lawrencium is strongly radioactive: it does not occur naturally and must be produced by artificial synthesis."},
                {"• Group 4 is the second group of transition metals in the periodic table.", "•  It contains the four elements titanium (Ti), zirconium (Zr), hafnium (Hf), and rutherfordium (Rf)", "• This group lies in the d-block of the periodic table, meaning the outermost electron is in the d-orbital.", "• As is typical for early transition metals, zirconium and hafnium have only the group oxidation state of +4 as a major one.", "• All the group 4 elements are hard, refractory metals.", "• Their inherent reactivity is completely masked due to the formation of a dense oxide layer that protects them from corrosion.", "• The first three of them occur naturally.", "• Rutherfordium is strongly radioactive: it does not occur naturally and must be produced by artificial synthesis.", "• As in all d-block elements, they have high melting and boiling points."},
                {"• Group 5 elements are also called pnictogens.", "• Group 5 contains vanadium (V), niobium (Nb), tantalum (Ta) and dubnium (Db).", "• This group lies in the d-block of the periodic table, meaning the outermost electron is in the d-orbital.", "• The lighter three Group 5 elements occur naturally and share similar properties. They are hard refractory metals under standard conditions.", "• The fourth element, dubnium, has been synthesized in laboratories, but it has not been found occurring in nature.", "• All elements in this group have 2 electrons in their outermost shell, though niobium curiously does not follow the trend with 1 electron in the outermost shell.", "• These elements have high melting and boiling points."},
                {"• Group 6 elements are also called chromium metals.", "• ts members are chromium (Cr), molybdenum (Mo), tungsten (W), and seaborgium (Sg).", "• These are all transition metals and chromium, molybdenum and tungsten are refractory metals.", "• The electron configuration of these elements do not follow a unified trend.", "•  The elements in the group have high melting points, and form volatile compounds in higher oxidation states.", "• The first three element occur naturally on Earth.","• Seaborgium is not found in nature but made in a laboratory."},
                {"• Group 7 is a group of chemical elements in the periodic table.", "• They are manganese (Mn), technetium (Tc), rhenium (Re), and bohrium (Bh).", "• Like most other groups, the members of this family show patterns in their electron configurations, having 2 electrons in the outermost shell.", "• Manganese is the only common Group 7 element with the fifth largest abundance in the Earth's crust of any metal.", "• All other elements are incredibly rare on earth(technetium, rhenium) or completely synthetic(Bohrium).", "• Only manganese has a role in the human body. It is an essential trace nutrient, with the body containing approx. 10 mg at any given time."},
                {"• Group 8 is a group of chemical elements in the periodic table.",  "• It consists of iron (Fe), ruthenium (Ru), osmium (Os) and hassium (Hs). They are all transition metals.", "• In the older group naming systems, this group was combined with groups 9 and 10 and called group \"VIIIB\"", "• The first three elements are silvery white metals.", "• Iron is a very common element that is used for things like steel and ferro-magnetic properties.", "• Ruthenium is mostly used for jewelery. Osmium is the densest element on the periodic table. It is used in ball tip pens.", "• Hassium is a very radioactive element that is not used for anything except research."},
                {"• Group 9 is a group of chemical elements in the periodic table.", "• Its members include Cobalt, Rhodium, Iridium and Meitnerium.", "• Like other groups, it shows a  trend in chemical behaviour but rhodium deviates from the pattern with 1 electron in its outermost shell.", "• In the older group systems, this group was combined with group 8 and 10 under the name \"VIIIB\"", "• All elements have 2 electron in the outermost shell except rhodium.", "• The first three elements are hard silvery white metals.", "• Cobalt is used to turn glass into a deep blue color. Rhodium is used in jewelry as a shiny metal.", "• Iridium is used as a hardening agent for platinum alloys. Isotopes of meitnerium are radioactive with short half-lives.", ""},
                {"• Group 10 is a group of chemical elements in the periodic table.", "• It consists of Nickel, Palladium, Platinum and perhaps chemically uncharacterized Darmstadtium.", "• All are d-block transition metals.", "• Although other group show pattern in electronic configuration, this group has a particularly weak one with palladium being an exceptional case.", "• Group 10 metals are white to light grey in color, and possess a high luster, a resistance to tarnish.", "• These elements are highly ductile ", "• Darmstadtium has not been isolated in pure form, and its properties have not been conclusively observed", "• Isotopes of darmstadtium are radioactive with short half-lives.", "• Group 10 elements are used in jewelry, elctroplating, catalysts, metal alloys, electrical components and super conductors.", "Nickel has an important role in the biochemistry of organisms, as part of the active center of enzymes."},
                {"• Group 11 is a group of chemical elements in the periodic table also known as the coinage metals due to their usage in minting coin.",  "• It consists of  copper (Cu), silver (Ag), and gold (Au). Roentgenium (Rg).", "• Due to the increase in the prices of gold and silver, they are no longer used as circulating currency.", "• But copper remains a common metal in coins to date, either in the form of copper clad coinage or cupronickel alloy.", "• The first three elements, copper, silver and gold occur naturally in their elemental form.", "• All the elements of the group except roentgenium have been known since prehistoric times.", "• All elements in this group have 1 electron in their outermost shell, although roentgenium is probably an exception.", "• All Group 11 elements are relatively inert, corrosion-resistant metals.", "• These elements have low electrical resistivity so they are used for wiring. Copper is the cheapest and most widely used."},
                {"• Group 12 is a group of chemical elements in the periodic table.",  "• It includes zinc (Zn), cadmium (Cd), mercury (Hg) and copernicium(Cn).", "•  Formerly this group was named IIB by CAS and old IUPAC system.", "• hey are all widely used in electric and electronic applications, as well as in various alloys.", "• The first two members of the group share similar properties as they are solid metals under standard conditions.", "• Mercury is the only metal that is a liquid at room temperature.", "• While zinc is very important in the biochemistry of living organisms, cadmium and mercury are both highly toxic.", "• As copernicium does not occur in nature, it has to be synthesized in the laboratory.", "• All elements of this group have 2 electron in their outermost shell.", "Group 12 elements are all soft, dimagnetic, divalent metals. They have the lowest melting points among all transition metals."},
                {"• Group 13 is a group of chemical elements in the periodic table, also known as the boron group.",  "• It comprises of Boron, Aluminium, Gallium, Indium, Thallium and chemically uncharacterized nihonium.", "• The elements in the boron group are characterized by having three valence electrons, also referred to as the triels.", "• Boron is commonly classified as a metalloid while the rest, with the possible exception of nihonium, are considered post-transition metals.", "•  Aluminium occurs widely on earth, and is the third most abundant element in the Earth's crust.", "• Gallium is found in the earth with an abundance of 13 ppm and Indium is the 61st most abundant element in the Earth's crust.", "• Thallium is found in moderate amounts throughout the planet while Nihonium is termed a synthetic element.", "• The boiling points and melting points of the carbon group tend to get lower with the heavier elements.", ""},
                {"• Group 14 is a group of chemical elements in the periodic table, also known as the carbon group.",  "• It consists of of carbon (C), silicon (Si), germanium (Ge), tin (Sn), lead (Pb), and flerovium (Fl).", "• It is also known as tetrels because it has four valence electrons.", "• They are also known a crystallogens or adamantogens.", "• An isolated, neutral group 14 atom has the s2 p2 configuration in the ground state.", "• These elements, especially carbon and silicon, have a strong propensity for covalent bonding, which usually brings the outer shell to eight electrons.", "• Carbon alone forms negative ions, in the form of carbide (C⁴⁻) ions.", "•  Silicon and germanium, both metalloids, each can form +4 ions.", "• Flerovium is the only synthetic element, radioactive in nature with very short half life(about 1.9 seconds)", "• The atomic radii of the carbon group elements tend to increase with increasing atomic number."},
                {"• Group 15 is a group of chemical elements in the periodic table, also known as the pnictogen and the nitrogen family.",  "• It consists of the elements nitrogen (N), phosphorus (P), arsenic (As), antimony (Sb), bismuth (Bi) and chemically uncharacterized Moscovium(Mc).", "• In CAS and the old IUPAC systems it was called Group VA and Group VB respectively.", "• This group has the defining characteristic that all the component elements have 5 electrons in their outermost shell.", "• They are therefore 3 electrons short of filling their outermost electron shell in their non-ionized state.", "• he most important elements of this group are nitrogen (N), which in its diatomic form is the principal component of air.", "• When oxidized or ionized, pnictogens typically take an oxidation state of +3 or +5.", "• Pnictogens can react with hydrogen to form pnictogen hydrides such as ammonia."},
                {"• Group 16 is a group of chemical elements in the periodic table, also known as the chalcogen or the oxygen family.",  "• It consists of the elements oxygen (O), sulfur (S), selenium (Se), tellurium (Te), and the radioactive element polonium (Po).", "• he chemically uncharacterized synthetic element livermorium (Lv) is predicted to be a chalcogen as well.", "• Sometimes oxygen is separated from the other chalcogens due to its very different chemical behaviour from the other members.", "• All of the chalcogens have six valence electrons, leaving them two electrons short of a full outer shell.", "• Their most common oxidation states are −2, +2, +4, and +6.", "• They have relatively low atomic radii, especially the lighter ones.", "• Lighter chalcogens are typically nontoxic in their elemental form, and are often critical to life, while the heavier chalcogens are typically toxic.", "• All of the solid, stable chalcogens are soft and do not conduct heat well. Electronegativity decreases towards the chalcogens with higher atomic numbers.", "• Density, melting and boiling points, and atomic and ionic radii[9] tend to increase towards the chalcogens with higher atomic numbers."},
                {"• Group 17 is a group of chemical elements in the periodic table, also known as the halogens.",  "• It comprises of fluorine (F), chlorine (Cl), bromine (Br), iodine (I), and astatine (At).", "• The artificially created element 117, tennessine (Ts), may also be a halogen.", "• The name \"halogen\" means \"salt-producing\" as they react with metals to form a wide range of ", "salts, including calcium fluoride, sodium chloride, silver bromide and potassium iodide.", "• The group of halogens is the only periodic table group that contains elements in three of the main states of matter at standard temperature and pressure.", "• All of the halogens form acids when bonded to hydrogen.", "• Halogens have seven electron in their outermost shell, one electron less of a full outer shell."},
                {"• Group 18 is a group of chemical elements in the periodic table, also referred to as group 0 or noble gases.",  "• The six naturally occurring noble gases are helium (He), neon (Ne), argon (Ar), krypton (Kr), xenon (Xe), and the radioactive radon (Rn).", "• Oganesson (Og) is a synthetically produced highly radioactive element, variously predicted to be another noble gas,", "• Under standard conditions, they are all odorless, colorless, monatomic gases with very low chemical reactivity.", "•  Noble gases are typically highly unreactive except when under particular extreme conditions.", "• The inertness of noble gases makes them very suitable in applications where reactions are not wanted.", "• Their outer shell of valence electrons is considered to be \"full\", giving them little tendency to participate in chemical reactions.", "• The melting and boiling points for a given noble gas are close together, differing by less than 10 °C; they are liquids over only a small temperature range. ", "• They all have a \"full\" outermost shell with an oxidation state of 0."},
        };

        new TextArea(frame, lines, 20, 20);

        JComboBox<String> groupComboBox = new JComboBox<>(new String[]{"1 - Alkali Metals", "2 - Alkaline Earth Metals", "3 - Scandium group", "4 - Titanium group", "5 - Vanadium group", "6 - Chromium group", "7 - Manganese group", "8 - Iron group", "9 - Cobalt group", "10 - Nickel group", "11 - Copper Group", "12 - Zinc Group", "13 - Gallium group", "14 - Germanium group", "15 - Pnictogens", "16 - Chalcogens", "17 - Halogens", "18 - Noble gases"});
        groupComboBox.setBounds(20, 450, 200, 40);
        groupComboBox.setFocusable(false);
        frame.add(groupComboBox);

        JButton submit = new JButton("Submit");
        submit.setFocusable(false);
        submit.setBounds(250, 450, 80, 40);
        submit.setFont(new Font("Open Sans", Font.PLAIN, 14));
        frame.add(submit);
        submit.addActionListener(e -> {

            // Taking the text from the Text field and converting it into an integer.
            int n = groupComboBox.getSelectedIndex() + 1;

            // The group title is group + the number entered and the lines of the group is accessed using the groupLines double array.
            new Group("Group "+(n), groupLines[n - 1]);

        });

        frame.setVisible(true);
    }
}
